version: '3.8'
services:
    app:
        image: ivandevelop/nodejs2025q2-service:0.1
        container_name: rest_service
        restart: always
        env_file: .env
        networks:
            - rest_network
        ports:
            - '${PORT}:${PORT}'

    db:
        image: postgres:13-alpine
        container_name: postgres_db
        restart: always
        env_file: .env
        networks:
            - rest_network
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - postgres_logs:/var/log/postgresql
        ports:
            - '${DB_PORT}:${DB_PORT}'
        depends_on:
            - app
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
            interval: 1s
            timeout: 5s
            retries: 10

    migrate:
        image: ivandevelop/nodejs2025q2-service:0.1
        container_name: migrate
        restart: 'on-failure'
        depends_on:
            db:
                condition: service_healthy
        networks:
            - rest_network
        env_file: .env
        command: npm run migrate

networks:
    rest_network:
        driver: ${NETWORK_DRIVER}

volumes:
    postgres_data:
    postgres_logs:
